name: "Build Extension"
description: "Builds the extension"

inputs:
  extension:
    required: true
    description: "Name of the extension to build"

runs:
  using: "composite"
  steps:
      - name: Test extension
        working-directory: ./extensions
        run: ./gradlew :${{ inputs.extension }}:test --scan --stacktrace --warning-mode all
        shell: bash

      - name: Build Extension
        working-directory: ./extensions
        run: ./gradlew :${{ inputs.extension }}:buildRelease --scan --stacktrace --warning-mode all
        shell: bash
